#!/bin/bash
#SBATCH -A nairr240405-gpu
#SBATCH -p gpu
#SBATCH --nodes=2
#SBATCH --ntasks=2
#SBATCH --job-name lorafinetune
#SBATCH --gres=gpu:1

module load conda
module use /home/x-apark4/privatemodules
module load conda-env/unsloth-py3.12.8

NODELIST=($(scontrol show hostnames $SLURM_JOB_NODELIST))

TRAIN_NODES="${NODELIST[@]:0:2}" 

srun --nodes=2 --ntasks=2 --nodelist="${NODELIST[@]:0:2}" accelerate launch \
     --config_file accelerate.yaml \
     --num_processes 1 \
     --gpus-per-node 1 \
     --num_machines 2 \
     --main_process_ip ${NODELIST[0]} \
     --machine_rank $SLURM_PROCID \
     --rdzv_backend c10d \
     multinode.py \

wait